#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/booking
#    username: root
#    password: root

spring:
  datasource:
    url: jdbc:mysql://168.119.132.30:3306/Booking
    username: root
    password: LCQcxx37460
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.springframework.security: DEBUG

