spring:
  datasource:
    url: jdbc:mysql://168.119.132.15:3306/Booking
    username: root
    password: VSInnl48944
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.security: DEBUG


springdoc:

  swagger-ui:
    path: /bezkoder-documentation
  api-docs:
    path: /bezkoder-api-docs

    tryItOutEnabled: true
    filter: true

bezkoder:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://168.119.132.18:8080

  app:
    jwtCookieName: Booking
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000
    stayLoggedInExpirationMs: 31536000000
schemes:
  - https
image:
  storage:
    location: /opt/tomcat/data


# http://localhost:8080/swagger-ui/index.html#
# http://168.119.132.18:8080/swagger-ui/index.html#


